apiVersion: v1
kind: Service
metadata:
  name: pr-devops-toolkit-1
  namespace: pr-devops-toolkit-1
spec:
  selector:
    app: pr-devops-toolkit-1-devops-toolkit
  type: NodePort
  ports:
  - port: 9000
    nodePort: 31000
    protocol: TCP
    targetPort: 80
